spring.application.name=risk-engine

newsapi.key=${NEWSAPI_KEY:}
groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-20b
alphavantage.api.key=${ALPHAVANTAGE_API_KEY:}